Final branch for the project:
Ali-0111/countries-info pull request #2
Opened 2023-05-12 20:11 UTC by Ali-0111

### Short Description
- I chose the api from coding Ninja [country API](https://api-ninjas.com/api/country)
- Files structures done as below:
  - [ ] src
       - [ ] pages
       - [ ] components
       - [ ] features
       - [ ] store
       - [ ] api.js
       - [ ] styles
       - [ ] images
       - [ ] icons
       - [ ] tests
       - [ ] app.js
       - [ ] index.js
- `Home` and `Details` pages will be rendered by `useNavigate()`
- Default view is `Home`
- `createAsynThunk` used with `axios` for fetching and update state
- `useDispatch` used for dispatching actions and api request
- `useEffect` used inside `app.js` to ensure avoiding extra dispatching actions.
- `Mocks` created for non-pure functions
- Pure functions rendered directly inside `.test.js` by using `render`
- render used from `@testing-library/react`
- [ ] a good tip for testing: `const { container } = render( <component />)`
- `react-test-renderer` library used for rendering routes and integration test

2023-05-12 21:51 UTC, GzimAsani requested changes
### Hello, @Ali-0111              :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with styling :+1: 

 ## Required Changes 

- [ ] Check the comments below :arrow_double_down: 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 21:51 UTC, GzimAsani commented on src/tests/Store.test.js
> +});
- [ ] You have on error from tests, kindly check into this 
![image](https://github.com/Ali-0111/countries-info/assets/62705947/7288c542-e862-44c6-8c87-2865f6bdd592)

2023-05-12 21:51 UTC, GzimAsani commented on src/api.js
> +const baseUrl = `${process.env.REACT_APP_API_BASE_URL}&&limit=20`;
- [ ] You need to provide the keys to the users because otherwise without them they can't check the data on your application

2023-05-12 21:51 UTC, GzimAsani commented on src/api.js
> +const baseUrl = `${process.env.REACT_APP_API_BASE_URL}&&limit=20`;
- [ ] I created my key and used the ninja API but your current setup I couldn't make it work the setup page. The same env was being used on form and on api file, but the one on form was throwing an error when I was trying to move to the details page

2023-05-12 21:51 UTC, GzimAsani commented on src/api.js
> +const baseUrl = `${process.env.REACT_APP_API_BASE_URL}&&limit=20`;
- [ ] It would be great if every country could be clickable on the card which would move them into the details page.
- [ ] It would be great if every country would be represented by an id or its name on the url instead of **detail** for each of them

2023-05-12 23:20 UTC, Ali-0111 commented
Hi, @GzimAsani 
Hope this message find you well.
in this sentencet, I could not get what you meant:
 - [ ] It would be great if every country would be represented by an id or its name on the url instead of detail for each of them
 please kindly provide clear information. It is not clear.

2023-05-12 23:21 UTC, Ali-0111 commented
> Hi, @GzimAsani Hope this message find you well. in this sentencet, I could not get what you meant:
> 
> * [ ]  It would be great if every country would be represented by an id or its name _on the url instead_ of detail for each of them
>   please kindly provide clear information. It is not clear.

2023-05-13 11:49 UTC, Ali-0111 commented
Hi, @team;
- [ ] I added unique routes for each card-country
- [ ] Broken lines removed from readme file
- [ ] Updated codes deployed

2023-05-13 12:27 UTC, Ali-0111 commented
- [ ] Tests passed
![image](https://github.com/Ali-0111/countries-info/assets/73581663/f034853e-4690-4059-8076-2f9962f5385b)

2023-06-27 17:58 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 14:33 UTC, merged